### PR TITLE
Fixes #202 : infinite redirection bug on password change

### LINKED ISSUE #202: Infinte redirection on password change
With a clean Solidus installation (sanbox or [heroku](http://soldemo.herokuapp.com/)) using `solidus_auth_devise`, when the user changes the password, they end up in an infinite loop of redirects.

### PR DESCRIPTION
**Pull request by nomad-mando**
**Issue:** Infinite redirection was happening when, config `signout_after_password_change` was set to true, and user tries to change the password.

**Root cause:** When `signout_after_password_change` is enabled, on password change the user gets logged out. But in controller (`Spree::UsersController#update`) we were redirecting the user to account page. This was resulting in unauthorized access and previous URL being same account_edit page, it results in infinite redirection loop. ([Unauthorized access logic here](https://github.com/solidusio/solidus_auth_devise/blob/v2.5.2/lib/spree/auth/engine.rb#L86) tries to redirect to previous page first, which seems correct.)

**Solution:** When user is logged out already we shouldn't redirect it to the account edit page, so changing it to redirect on log_in page.

Fixes #202

### CODE REVIEW

File: lib/controllers/frontend/spree/users_controller.rb [hunk 1]
```diff
@@ -28,14 +28,13 @@ def create
...
     if @user.update(user_params)
       spree_current_user.reload
+      redirect_url = spree.account_url
 
       if params[:user][:password].present?
         # this logic needed b/c devise wants to log us out after password changes
-        unless Spree::Auth::Config[:signout_after_password_change]
-          bypass_sign_in(@user)
-        end
+        Spree::Auth::Config[:signout_after_password_change] ? redirect_url = spree.login_url : bypass_sign_in(@user)
```
Comment (aldesantis) [inline lib/controllers/frontend/spree/users_controller.rb:35]: I find this inline assignment in a ternary operator quite hard to read. 😛 Could you just turn this into a regular if condition?

**Review by aldesantis — CHANGES_REQUESTED** [review]
Thanks @nomad-mando, just a quick comment on readability!

**Comment by nomad-mando** [comment]
Thanks @aldesantis, I have addressed the comment now 👍

**Comment by nomad-mando** [comment]
@aldesantis seems like some feature test started failing after that code refactoring. It doesn't look related to my change. Will check why it started failing later when I get chance.

**Comment by nomad-mando** [comment]
same specs are also failing in master, I suspect they started failing after #203 got merged.

**Review by aldesantis — APPROVED** [review]

**Comment by aldesantis** [comment]
@nomad-mando you're right, the failing specs are not related to your change.

Code-wise, this is looking good. Can you just squash the commits together so we don't pollute the history?

**Review by jarednorman — APPROVED** [review]
Looks good, just need things squashed and should be good.

**Comment by nomad-mando** [comment]
@aldesantis / @jarednorman Done 👍 squashed both commits in to a single commit.
